/* Data views: migration model, network, national-vs-family chart, keyword mining.
   All data comes from data/family.js, generated by analysis/build.py. */
(() => {
  "use strict";

  const F = window.FAMILY;
  const M = window.MINED;
  if (!F) return;

  const reduceMotion = window.matchMedia("(prefers-reduced-motion: reduce)").matches;
  const css = (name) => getComputedStyle(document.documentElement).getPropertyValue(name).trim();
  const el = (tag, cls, html) => {
    const node = document.createElement(tag);
    if (cls) node.className = cls;
    if (html !== undefined) node.innerHTML = html;
    return node;
  };
  const esc = (t) => String(t).replace(/[&<>"]/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" }[c]));

  const persons = new Map(F.persons.map((p) => [p.id, p]));
  const places = new Map(F.places.map((p) => [p.id, p]));
  const shortName = (id) => {
    const p = persons.get(id);
    return p ? p.name : id;
  };
  // Canada is drawn east of China so routes cross the Pacific.
  const ll = (place) => [place.lat, place.lng < 0 ? place.lng + 360 : place.lng];

  // A residence covers [from, to); the move year belongs to the new place.
  const lastTo = new Map();
  F.residences.forEach((r) => lastTo.set(r.person, Math.max(lastTo.get(r.person) || 0, r.to)));
  const covers = (r, year) => year >= r.from && (year < r.to || (r.to === lastTo.get(r.person) && year === r.to));

  function whereAt(year) {
    const at = new Map();
    F.residences.forEach((r) => {
      if (covers(r, year)) {
        if (!at.has(r.place)) at.set(r.place, []);
        if (!at.get(r.place).some((x) => x.person === r.person)) at.get(r.place).push(r);
      }
    });
    return at;
  }

  /* ================= Migration model ================= */

  function buildMigration() {
    const range = document.getElementById("year");
    const out = document.getElementById("year-out");
    const panel = document.getElementById("year-panel");
    const legsList = document.getElementById("legs");
    const playBtn = document.getElementById("play");
    const mapEl = document.getElementById("map");
    if (!range || !panel) return;

    let map = null;
    let dynamic = null;
    let scope = "";
    const hasLeaflet = typeof L !== "undefined";

    if (hasLeaflet) {
      map = L.map(mapEl, { scrollWheelZoom: false, zoomSnap: 0.25, worldCopyJump: false, fadeAnimation: false });
      L.tileLayer("https://server.arcgisonline.com/ArcGIS/rest/services/World_Topo_Map/MapServer/tile/{z}/{y}/{x}", {
        attribution: "Tiles &copy; Esri and the GIS User Community",
        maxZoom: 16
      }).addTo(map);
      dynamic = L.layerGroup().addTo(map);
    } else {
      document.getElementById("map-fallback").hidden = false;
    }

    const arc = (a, b, bend = 0.18) => {
      const [lat1, lng1] = a;
      const [lat2, lng2] = b;
      const cLat = (lat1 + lat2) / 2 + (lng2 - lng1) * bend;
      const cLng = (lng1 + lng2) / 2 - (lat2 - lat1) * bend;
      const pts = [];
      for (let t = 0; t <= 1.0001; t += 0.04) {
        const u = 1 - t;
        pts.push([u * u * lat1 + 2 * u * t * cLat + t * t * lat2, u * u * lng1 + 2 * u * t * cLng + t * t * lng2]);
      }
      return pts;
    };

    const moveButtons = F.moves.map((m) => {
      const li = el("li");
      const btn = el("button", "leg",
        `<span class="leg__num" aria-hidden="true">${m.year}</span>` +
        `<span class="leg__title">${esc(m.label)}</span>` +
        `<span class="leg__text">${esc(m.text)}${m.approx ? " Year approx." : ""}</span>`);
      btn.type = "button";
      btn.setAttribute("aria-pressed", "false");
      btn.addEventListener("click", () => {
        stop();
        setYear(m.year);
        range.focus({ preventScroll: true });
      });
      li.appendChild(btn);
      legsList.appendChild(li);
      return [m, btn];
    });

    function render(year) {
      const ink = css("--ink");
      const violet = css("--violet");
      const face = css("--face");
      const at = whereAt(year);

      moveButtons.forEach(([m, b]) => b.setAttribute("aria-pressed", String(m.year === year)));

      // panel
      let html = `<p class="year-panel__year">${year}</p>`;
      if (at.size) {
        html += `<h3>Where everyone was</h3><ul class="where">`;
        [...at.entries()].forEach(([pid, rs]) => {
          const pl = places.get(pid);
          html += `<li><b>${esc(pl.name)}</b> <span class="zh" lang="zh-Hans">${esc(pl.zh)}</span><span>${rs.map((r) => esc(shortName(r.person)) + (r.approx ? "*" : "")).join(", ")}</span></li>`;
        });
        html += "</ul>";
      }
      const offMap = [];
      if (year >= 1951 && year < 1955) offMap.push("Li Hanqing: in prison, location not recorded");
      if (year > 1981 && year <= 1995) offMap.push("Li Hanqing: later years not recorded");
      if (year > 1966 && year <= 1995) offMap.push("Li Zhilan: married far away, place not recorded");
      if (offMap.length) html += `<p class="where__off">${offMap.map(esc).join("<br>")}</p>`;
      const active = F.events.filter((e) => year >= e.from && year <= e.to);
      if (active.length) {
        html += `<h3>Under way</h3><ul class="happening">`;
        active.forEach((e) => {
          html += `<li class="happening--${e.scope}"><span class="lens">${e.scope === "family" ? "Family" : esc(e.lens[0].toUpperCase() + e.lens.slice(1))}</span><b>${esc(e.label)}</b> ${esc(e.text)}</li>`;
        });
        html += "</ul>";
      }
      if (at.size && [...at.values()].flat().some((r) => r.approx)) html += `<p class="where__off">* Year of residence is approximate.</p>`;
      panel.innerHTML = html;

      if (!map) return;
      dynamic.clearLayers();

      // routes already travelled
      F.moves.filter((m) => m.year <= year).forEach((m) => {
        const recent = year - m.year <= 3;
        L.polyline(arc(ll(places.get(m.from)), ll(places.get(m.to))), {
          color: recent ? violet : ink, weight: recent ? 3.5 : 2, opacity: recent ? 1 : 0.45,
          dashArray: recent ? null : "2 7", lineCap: "round"
        }).addTo(dynamic);
      });

      // occupied places
      at.forEach((rs, pid) => {
        const pl = places.get(pid);
        L.circleMarker(ll(pl), {
          radius: 5 + rs.length * 1.6, color: ink, weight: 2, fillColor: face, fillOpacity: 1
        }).bindTooltip(`${esc(pl.name)} <small>${rs.length}</small>`, {
          permanent: true, direction: "right", offset: [8, 0], className: "place-label"
        }).addTo(dynamic);
      });

      const abroad = [...at.keys()].some((k) => places.get(k).type === "abroad");
      const next = abroad ? "world" : "china";
      if (next !== scope) {
        scope = next;
        const pts = abroad
          ? [ll(places.get("wuhan")), ll(places.get("waterloo")), ll(places.get("montreal"))]
          : [ll(places.get("village")), ll(places.get("wuhan")), ll(places.get("changsha"))];
        const first = !map._loaded;
        if (first || reduceMotion) map.fitBounds(L.latLngBounds(pts), { padding: [60, 60], maxZoom: 7, animate: false });
        else map.flyToBounds(L.latLngBounds(pts), { padding: [60, 60], maxZoom: 7, duration: 0.9 });
      }
    }

    function setYear(y) {
      const year = Math.max(1910, Math.min(2026, Math.round(y)));
      range.value = year;
      out.value = year;
      out.textContent = year;
      render(year);
    }

    let timer = null;
    function stop() {
      if (timer) clearInterval(timer);
      timer = null;
      playBtn.textContent = "Play";
      playBtn.setAttribute("aria-pressed", "false");
    }
    playBtn.addEventListener("click", () => {
      if (timer) return stop();
      if (+range.value >= 2026) setYear(1910);
      playBtn.textContent = "Pause";
      playBtn.setAttribute("aria-pressed", "true");
      timer = setInterval(() => {
        const y = +range.value + 1;
        setYear(y);
        if (y >= 2026) stop();
      }, reduceMotion ? 260 : 140);
    });
    range.addEventListener("input", () => {
      stop();
      setYear(+range.value);
    });

    setYear(+range.value);
  }

  /* ================= Network ================= */

  const contextLinks = [
    ["f1951", "e1950"], ["f1951", "e1950b"], ["f1945a", "e1937"], ["f1945a", "e1945"], ["f1959", "e1953"], ["f1963", "e1966"], ["f1981", "e1982"], ["f1982", "e1982"], ["f2000", "e1978"], ["f2000", "e1998"], ["e1958", "villagecom"]
  ];

  function buildNetwork() {
    const host = document.getElementById("graph");
    const detail = document.getElementById("graph-detail");
    if (!host || typeof d3 === "undefined") return;

    const nodes = [];
    const add = (id, label, kind, info) => nodes.push({ id, label, kind, info });
    F.persons.forEach((p) => add(p.id, p.name, "person", [p.role, p.education, p.occupation].filter(Boolean).join(". ")));
    F.places.forEach((p) => add(p.id, p.name, "place", p.approx ? "Position approximate." : p.type));
    F.groups.forEach((g) => add(g.id, g.name, "group", g.text));
    const usedNational = new Set(contextLinks.flat());
    F.events.forEach((e) => {
      if (e.scope === "family" && e.persons && e.persons.length && !/born$/.test(e.label)) add(e.id, e.label, "event", e.text);
      if (e.scope === "national" && usedNational.has(e.id)) add(e.id, e.label, "national", e.text);
    });
    const ids = new Set(nodes.map((n) => n.id));

    const links = [];
    const link = (s, t, type) => { if (ids.has(s) && ids.has(t)) links.push({ source: s, target: t, type }); };
    F.relations.forEach((r) => link(r.source, r.target, r.type));
    const lived = new Set();
    F.residences.forEach((r) => {
      const k = r.person + ">" + r.place;
      if (!lived.has(k)) { lived.add(k); link(r.person, r.place, "lived in"); }
    });
    F.events.forEach((e) => (e.persons || []).forEach((p) => link(p, e.id, "experienced")));
    contextLinks.forEach(([a, b]) => link(a, b, "part of"));

    const width = Math.max(host.clientWidth || 800, 720);
    const height = 760;
    const sim = d3.forceSimulation(nodes)
      .force("link", d3.forceLink(links).id((d) => d.id).distance((l) => (l.type === "parent" ? 80 : 120)).strength(0.4))
      .force("charge", d3.forceManyBody().strength(-480))
      .force("center", d3.forceCenter(width / 2, height / 2))
      .force("collide", d3.forceCollide(width < 600 ? 24 : 40))
      .force("x", d3.forceX(width / 2).strength(width < 600 ? 0.06 : 0.02))
      .force("y", d3.forceY(height / 2).strength(width < 600 ? 0.1 : 0.05))
      .stop();
    const clamp = () => nodes.forEach((n) => {
      n.x = Math.max(30, Math.min(width - 150, n.x));
      n.y = Math.max(24, Math.min(height - 24, n.y));
    });
    for (let i = 0; i < 400; i++) { sim.tick(); clamp(); }

    const svg = d3.select(host).append("svg").attr("viewBox", `0 0 ${width} ${height}`).attr("width", width).attr("height", height);
    const linkSel = svg.append("g").attr("class", "g-links").selectAll("line").data(links).join("line")
      .attr("x1", (d) => d.source.x).attr("y1", (d) => d.source.y).attr("x2", (d) => d.target.x).attr("y2", (d) => d.target.y)
      .attr("class", (d) => "g-link g-link--" + d.type.replace(/\s/g, "-"));

    const symbol = { person: d3.symbolCircle, place: d3.symbolSquare, group: d3.symbolTriangle, event: d3.symbolDiamond, national: d3.symbolDiamond };
    const size = { person: 300, place: 220, group: 240, event: 170, national: 170 };

    const nodeSel = svg.append("g").selectAll("g").data(nodes).join("g")
      .attr("class", (d) => "g-node g-node--" + d.kind)
      .attr("transform", (d) => `translate(${d.x},${d.y})`)
      .attr("tabindex", 0).attr("role", "button")
      .attr("aria-label", (d) => `${d.label}, ${d.kind === "national" ? "national event" : d.kind}`);
    nodeSel.append("title").text((d) => d.label);
    nodeSel.append("circle").attr("r", 22).attr("class", "g-hit");
    nodeSel.append("path").attr("d", (d) => d3.symbol(symbol[d.kind], size[d.kind])());
    nodeSel.append("text").attr("x", 12).attr("y", 4).text((d) => d.label)
      .attr("class", (d) => (d.kind === "person" || d.kind === "place" ? "g-label" : "g-label g-label--minor"));

    const neighbours = (id) => {
      const set = new Set([id]);
      links.forEach((l) => {
        if (l.source.id === id) set.add(l.target.id);
        if (l.target.id === id) set.add(l.source.id);
      });
      return set;
    };

    function select(d) {
      const near = neighbours(d.id);
      nodeSel.classed("is-dim", (n) => !near.has(n.id)).classed("is-near", (n) => near.has(n.id)).classed("is-on", (n) => n.id === d.id);
      linkSel.classed("is-dim", (l) => l.source.id !== d.id && l.target.id !== d.id);
      const rows = links.filter((l) => l.source.id === d.id || l.target.id === d.id)
        .map((l) => {
          const other = l.source.id === d.id ? l.target : l.source;
          const verb = l.source.id === d.id ? l.type : ({ "cut off contact": "contact cut off by", parent: "child of", member: "includes", studied: "attended by", worked: "workplace of", "lived in": "home of", experienced: "involved", "part of": "context for" }[l.type] || l.type);
          return `<li><span>${esc(verb)}</span> ${esc(other.label)}</li>`;
        }).join("");
      detail.innerHTML = `<p class="graph-detail__name">${esc(d.label)}</p><p>${esc(d.info || "")}</p><ul>${rows}</ul>`;
    }
    nodeSel.on("click", (e, d) => select(d)).on("keydown", (e, d) => {
      if (e.key === "Enter" || e.key === " ") { e.preventDefault(); select(d); }
    });
    svg.on("click", (e) => {
      if (e.target === svg.node()) {
        nodeSel.classed("is-dim", false).classed("is-on", false).classed("is-near", false);
        linkSel.classed("is-dim", false);
      }
    });

    const legend = document.getElementById("graph-legend");
    [["person", "Person"], ["place", "Place"], ["group", "Community or institution"], ["event", "Family event"], ["national", "National event"]].forEach(([k, label]) => {
      const li = el("li", "legend__item legend__item--" + k);
      li.innerHTML = `<svg width="18" height="18" viewBox="-9 -9 18 18" aria-hidden="true"><path d="${d3.symbol(symbol[k], size[k] * 0.55)()}"/></svg>${label}`;
      legend.appendChild(li);
    });
    [["parent", "Parent and child"], ["cut", "Contact cut off, 1963 to 1981"]].forEach(([k, label]) => {
      legend.appendChild(el("li", "legend__item legend__edge legend__edge--" + k, `<i aria-hidden="true"></i>${label}`));
    });

    const table = document.getElementById("graph-table");
    table.innerHTML = "<thead><tr><th scope=\"col\">From</th><th scope=\"col\">Connection</th><th scope=\"col\">To</th></tr></thead><tbody>" +
      links.map((l) => `<tr><td>${esc(l.source.label)}</td><td>${esc(l.type)}</td><td>${esc(l.target.label)}</td></tr>`).join("") + "</tbody>";
  }

  /* ================= National change vs the family ================= */

  const COHORT = ["zhiyuan", "zhiqing", "zhiping", "zhilan", "zhikang", "zhimei"];

  // Share of the six surviving children living in a town or city, 1950-1995.
  function familyUrbanShare() {
    const rows = [];
    for (let y = 1950; y <= 1995; y++) {
      let urban = 0;
      COHORT.forEach((pid) => {
        const r = F.residences.find((x) => x.person === pid && covers(x, y));
        if (r && places.get(r.place).type !== "village") urban += 1;
      });
      rows.push([y, Math.round((urban / COHORT.length) * 1000) / 10, urban]);
    }
    return rows;
  }

  function buildMacro() {
    const host = document.getElementById("macro-chart");
    if (!host || typeof d3 === "undefined") return;

    const fam = familyUrbanShare();
    const series = [
      { key: "urban", label: "China: urban population", data: F.macro.urban_share, cls: "s-urban" },
      { key: "farm", label: "China: jobs in farming", data: F.macro.primary_employment_share, cls: "s-farm" },
      { key: "family", label: "Li siblings: share of the six living in a town or city", data: fam.map(([y, v]) => [y, v]), cls: "s-family", step: true }
    ];

    const width = Math.max(host.clientWidth, 320);
    const narrow = width < 640;
    const height = narrow ? 320 : 400;
    const m = { top: 20, right: narrow ? 16 : 190, bottom: 36, left: 44 };
    const x = d3.scaleLinear().domain([1945, 2026]).range([m.left, width - m.right]);
    const y = d3.scaleLinear().domain([0, 100]).range([height - m.bottom, m.top]);

    const svg = d3.select(host).append("svg").attr("viewBox", `0 0 ${width} ${height}`).attr("width", "100%").attr("height", height)
      .attr("role", "img").attr("aria-label", "Line chart comparing China's urban share and farm employment with the Li family's urban share, 1945 to 2026. The table below has the values.");

    svg.append("g").attr("class", "axis axis--y").attr("transform", `translate(${m.left},0)`)
      .call(d3.axisLeft(y).ticks(5).tickSize(-(width - m.left - m.right)).tickFormat((d) => d + "%"))
      .call((g) => g.select(".domain").remove());
    svg.append("g").attr("class", "axis axis--x").attr("transform", `translate(0,${height - m.bottom})`)
      .call(d3.axisBottom(x).ticks(narrow ? 5 : 9).tickFormat(d3.format("d")).tickSize(0).tickPadding(10))
      .call((g) => g.select(".domain").remove());

    // family events as quiet reference ticks
    [[1950, "Land reform"], [1958, "Hukou rules"], [1978, "Reform"], [1998, "Housing reform"]].forEach(([yr, label]) => {
      svg.append("line").attr("class", "macro__event").attr("x1", x(yr)).attr("x2", x(yr)).attr("y1", m.top).attr("y2", height - m.bottom);
      if (!narrow) svg.append("text").attr("class", "macro__event-label").attr("x", x(yr) + 4).attr("y", m.top + 10).text(label);
    });

    series.forEach((s) => {
      const line = d3.line().x((d) => x(d[0])).y((d) => y(d[1]));
      if (s.step) line.curve(d3.curveStepAfter);
      svg.append("path").attr("class", "macro__line " + s.cls).attr("d", line(s.data));
      if (!s.step) svg.append("g").selectAll("circle").data(s.data).join("circle")
        .attr("class", "macro__dot " + s.cls).attr("cx", (d) => x(d[0])).attr("cy", (d) => y(d[1])).attr("r", 4);
      if (!narrow) {
        const last = s.data[s.data.length - 1];
        const dy = s.key === "urban" ? -6 : s.key === "farm" ? 14 : 4;
        svg.append("text").attr("class", "macro__end " + s.cls).attr("x", x(last[0]) + 8).attr("y", y(last[1]) + dy)
          .text(s.key === "family" ? "Li siblings" : s.key === "urban" ? "China: urban" : "China: farm jobs");
      }
    });

    const legend = el("ul", "legend");
    series.forEach((s) => legend.appendChild(el("li", "legend__item legend__line " + s.cls, `<i aria-hidden="true"></i>${esc(s.label)}`)));
    host.prepend(legend);

    // hover and keyboard crosshair
    const interp = (data, yr) => {
      if (yr < data[0][0] || yr > data[data.length - 1][0]) return null;
      for (let i = 0; i < data.length - 1; i++) {
        const [x0, v0] = data[i];
        const [x1, v1] = data[i + 1];
        if (yr >= x0 && yr <= x1) return { v: v0 + ((v1 - v0) * (yr - x0)) / (x1 - x0), exact: yr === x0 || yr === x1 };
      }
      return { v: data[data.length - 1][1], exact: true };
    };
    const famAt = new Map(fam.map(([yr, v, n]) => [yr, [v, n]]));
    const cross = svg.append("line").attr("class", "macro__cross").attr("y1", m.top).attr("y2", height - m.bottom).style("opacity", 0);
    const tip = el("div", "tooltip");
    tip.hidden = true;
    host.appendChild(tip);

    function show(yr) {
      yr = Math.max(1945, Math.min(2026, Math.round(yr)));
      cross.attr("x1", x(yr)).attr("x2", x(yr)).style("opacity", 1);
      const u = interp(F.macro.urban_share, yr);
      const f = interp(F.macro.primary_employment_share, yr);
      const fm = famAt.get(yr);
      tip.innerHTML = `<b>${yr}</b>` +
        (u ? `<span><i class="s-urban"></i>China urban ${u.exact ? "" : "≈"}${u.v.toFixed(1)}%</span>` : "") +
        (f ? `<span><i class="s-farm"></i>China farm jobs ${f.exact ? "" : "≈"}${f.v.toFixed(1)}%</span>` : "") +
        (fm ? `<span><i class="s-family"></i>Li siblings ${fm[0]}% (${fm[1]} of 6)</span>` : "");
      tip.hidden = false;
      const left = Math.min(x(yr) / width * host.clientWidth + 12, host.clientWidth - 230);
      tip.style.left = Math.max(0, left) + "px";
      tip.style.top = "56px";
      svg.attr("data-year", yr);
    }
    const hide = () => { cross.style("opacity", 0); tip.hidden = true; };
    svg.on("pointermove", (e) => {
      const [px] = d3.pointer(e);
      show(x.invert(px));
    }).on("pointerleave", hide);
    svg.attr("tabindex", 0).on("keydown", (e) => {
      const cur = +svg.attr("data-year") || 1978;
      if (e.key === "ArrowRight") { e.preventDefault(); show(cur + 1); }
      if (e.key === "ArrowLeft") { e.preventDefault(); show(cur - 1); }
    }).on("focus", () => show(+svg.attr("data-year") || 1978)).on("blur", hide);

    const table = document.getElementById("macro-table");
    const years = [1949, 1952, 1955, 1956, 1960, 1978, 1982, 1990, 2000, 2010, 2020];
    const val = (data, yr) => { const hit = data.find((d) => d[0] === yr); return hit ? hit[1] + "%" : ""; };
    table.innerHTML = `<thead><tr><th scope="col">Year</th><th scope="col">China urban population</th><th scope="col">China jobs in farming</th><th scope="col">Li siblings in a town or city</th></tr></thead><tbody>` +
      years.map((yr) => `<tr><td>${yr}</td><td>${val(F.macro.urban_share, yr)}</td><td>${val(F.macro.primary_employment_share, yr)}</td><td>${famAt.has(yr) ? famAt.get(yr)[0] + "% (" + famAt.get(yr)[1] + " of 6)" : ""}</td></tr>`).join("") + "</tbody>";
  }

  /* ================= Keyword mining ================= */

  function buildMined() {
    const host = document.getElementById("mined");
    if (!host || !M) return;
    const gens = Object.keys(M.generations);
    const tabs = document.getElementById("mined-tabs");
    const meta = document.getElementById("mined-meta");
    const zhGen = { g2: "第二代", g3: "第三代", g4: "第四代" };

    meta.textContent = `Corpus: ${M.corpus_label}. ` + gens.map((g) => { const G = M.generations[g]; return G.words ? `${G.label} about ${G.words.toLocaleString("en")} words` : `${G.label} ${G.characters.toLocaleString("en")} characters`; }).join(", ") + `. Method: ${M.method}.`;

    function render(gid) {
      const info = M.generations[gid];
      [...tabs.querySelectorAll("button")].forEach((b) => b.setAttribute("aria-selected", String(b.dataset.gen === gid)));
      const max = Math.max(1, ...M.dimensions.flatMap((d) => d.codes[gid].map((r) => r.count)));
      host.innerHTML = "";
      host.setAttribute("aria-label", `${info.label}: keyword counts by dimension`);
      M.dimensions.forEach((d) => {
        const col = el("div", "key-col");
        const total = d.codes[gid].reduce((sum, r) => sum + r.count, 0);
        col.appendChild(el("h3", "", `${esc(d.label)} <span class="zh" lang="zh-Hans">${esc(d.zh)}</span><small>${esc(d.question)} ${total} matches.</small>`));
        const ol = el("ol", "key-list");
        [...d.codes[gid]].sort((x, y) => y.count - x.count).forEach((r) => {
          const li = el("li", "key-row" + (r.count ? "" : " key-row--zero"));
          li.tabIndex = 0;
          li.title = `${r.count} occurrences, ${r.per10k} per 10,000 tokens`;
          li.setAttribute("aria-label", `${r.term}, ${r.en}: ${r.count} occurrences`);
          li.innerHTML =
            `<span class="key-term"><span class="zh" lang="zh-Hans">${esc(r.term)}</span><span class="key-en">${esc(r.en)}</span></span>` +
            `<span class="key-bar"><i style="width:${(r.count / max) * 100}%"></i><b>${r.count}</b></span>`;
          ol.appendChild(li);
        });
        col.appendChild(ol);
        host.appendChild(col);
      });
    }

    gens.forEach((g) => {
      const info = M.generations[g];
      const b = el("button", "tab", `${esc(info.label)} <span lang="zh-Hans">${zhGen[g] || ""}</span>`);
      b.type = "button";
      b.setAttribute("role", "tab");
      b.dataset.gen = g;
      b.addEventListener("click", () => render(g));
      b.addEventListener("keydown", (e) => {
        if (e.key !== "ArrowRight" && e.key !== "ArrowLeft") return;
        const list = [...tabs.querySelectorAll("button")];
        const next = list[(list.indexOf(b) + (e.key === "ArrowRight" ? 1 : list.length - 1)) % list.length];
        next.focus();
        render(next.dataset.gen);
      });
      tabs.appendChild(b);
    });
    render(gens[0]);
  }

  /* ================= Keyword marking demo ================= */

  const EXAMPLES = {
    g2: "Land reform came in 1951. The property was confiscated and the family fell into bankruptcy and hardship. My grandfather kept studying, left Taoyuan for school in Changde, and in 1955 went to university in Wuhan to study engineering and construction. After graduating he found work at a factory.",
    g3: "My parents were born in 1973. They grew up with reform and opening and economic growth, got a full education, and later settled in Wuhan, where they cared most about stability, income, and buying a home.",
    g4: "My generation faces involution, competition, and pressure in finding a job. Many of us choose to study abroad, apply to universities and majors overseas, and think hard about the future and our identity."
  };

  // Extra English forms for codebook terms, keyed by the Chinese term.
  const EN_EXTRA = {
    "战争": ["wars", "wartime"], "逃难": ["flee", "fled", "fleeing", "refugee", "refugees"], "地主": ["landlords"],
    "没收": ["confiscated", "confiscate"], "破产": ["bankrupt"], "困难": ["hardships", "difficulties"],
    "读书": ["study", "studied", "studies"], "学习": ["learn", "learned", "learnt"], "大学": ["college", "colleges", "universities"],
    "学校": ["schools"], "考试": ["exam"], "工作": ["job", "jobs", "career", "worked", "working"], "工程": ["engineer", "engineers"],
    "教育": ["educated"], "城市": ["cities", "urban"], "留学": ["study abroad", "studied abroad"], "出国": ["abroad", "go abroad", "went abroad"],
    "海外": ["overseas"], "美国": ["US", "U.S.", "America", "American"], "加拿大": ["Canadian"],
    "移民": ["immigration", "immigrate", "emigrate", "emigrated"], "竞争": ["compete", "competitive"], "压力": ["stress", "stressed"],
    "焦虑": ["anxious"], "就业": ["employed"], "实习": ["intern", "interns"], "申请": ["apply", "applied", "application"],
    "成绩": ["grade", "score", "scores"], "专业": ["majors"], "房贷": ["mortgages"], "买房": ["buy a home", "bought a home", "buy a house", "bought a house"],
    "房子": ["house", "houses", "apartment", "home"], "住房": ["housing"], "工资": ["salary", "salaries", "wage"], "稳定": ["stable", "security"],
    "失业": ["unemployed", "jobless"], "养老": ["retirement", "pension"], "解放": ["liberated"], "改革开放": ["reform and opening up"],
    "城市化": ["urbanisation"], "全球化": ["globalisation", "global"], "疫情": ["covid", "covid-19"], "科技": ["tech"], "互联网": ["online"],
    "发展": ["develop", "growth"], "机会": ["opportunities", "chance", "chances"], "定居": ["settle", "settled"], "搬家": ["moved house", "move house"],
    "农村": ["rural", "village"], "老家": ["hometown"], "离开": ["leave", "left"], "联系": ["contact", "in touch"]
  };

  function buildDemo() {
    const input = document.getElementById("demo-text");
    const marked = document.getElementById("demo-marked");
    const countsEl = document.getElementById("demo-counts");
    if (!input || !M) return;

    const dims = M.dimensions.map((d) => ({ id: d.id, label: d.label, zh: d.zh }));
    const zhDims = new Map();
    const enDims = new Map();
    const addTo = (map, key, dimId) => {
      if (!key) return;
      if (!map.has(key)) map.set(key, new Set());
      map.get(key).add(dimId);
    };
    const englishForms = (gloss) => gloss.split(/,\s*|\s+or\s+/).map((x) => x.trim().replace(/^(the|a|an)\s+/i, "").toLowerCase()).filter(Boolean);

    M.dimensions.forEach((d) => Object.values(d.codes).forEach((rows) => rows.forEach((r) => {
      r.term.split("/").forEach((t) => {
        addTo(zhDims, t, d.id);
        (EN_EXTRA[t] || []).forEach((e) => addTo(enDims, e.toLowerCase(), d.id));
      });
      englishForms(r.en).forEach((e) => addTo(enDims, e, d.id));
    })));

    const escRe = (x) => x.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
    const byLen = (a, b) => b.length - a.length;
    const enPattern = [...enDims.keys()].sort(byLen).map(escRe).join("|");
    const zhPattern = [...zhDims.keys()].filter((t) => /[^\x00-\x7f]/.test(t)).sort(byLen).map(escRe).join("|");
    const matcher = new RegExp(`(\\b(?:${enPattern})(?:es|s)?\\b)|(${zhPattern})`, "gi");

    const dimsFor = (hit) => {
      if (zhDims.has(hit)) return zhDims.get(hit);
      const low = hit.toLowerCase();
      return enDims.get(low) || enDims.get(low.replace(/es$/, "")) || enDims.get(low.replace(/s$/, ""));
    };

    function run() {
      const text = input.value;
      const tally = Object.fromEntries(dims.map((d) => [d.id, 0]));
      let html = "";
      let last = 0;
      for (const m of text.matchAll(matcher)) {
        const hit = m[0];
        const set = dimsFor(hit);
        if (!set) continue;
        const ds = [...set];
        ds.forEach((id) => { tally[id] += 1; });
        const names = ds.map((id) => dims.find((d) => d.id === id).label).join(", ");
        html += esc(text.slice(last, m.index)) + `<mark class="dim-${ds[0]}" title="${esc(names)}">${esc(hit)}</mark>`;
        last = m.index + hit.length;
      }
      html += esc(text.slice(last));
      marked.innerHTML = text.trim() ? html.replace(/\n/g, "<br>") : `<span class="demo__empty">Marked text appears here.</span>`;
      countsEl.innerHTML = dims.map((d) => `<li class="dim-${d.id}"><i aria-hidden="true"></i>${esc(d.label)} <span lang="zh-Hans">${esc(d.zh)}</span><b>${tally[d.id]}</b></li>`).join("");
    }

    input.addEventListener("input", run);
    document.querySelectorAll("[data-example]").forEach((b) => b.addEventListener("click", () => {
      input.value = b.dataset.example === "clear" ? "" : EXAMPLES[b.dataset.example];
      run();
      input.focus({ preventScroll: true });
    }));
    input.value = EXAMPLES.g2;
    run();
  }

  const start = () => {
    [buildMigration, buildNetwork, buildMacro, buildMined, buildDemo].forEach((fn) => {
      try { fn(); } catch (err) { console.error(fn.name, err); }
    });
  };
  if (document.readyState === "complete") start();
  else window.addEventListener("load", start);
})();
