/* Data views: migration model, network, national-vs-family chart, keyword mining.
   All data comes from data/family.js, generated by analysis/build.py. */
(() => {
  "use strict";

  const F = window.FAMILY;
  const M = window.MINED;
  if (!F) return;

  const reduceMotion = window.matchMedia("(prefers-reduced-motion: reduce)").matches;
  const css = (name) => getComputedStyle(document.documentElement).getPropertyValue(name).trim();
  const el = (tag, cls, html) => {
    const node = document.createElement(tag);
    if (cls) node.className = cls;
    if (html !== undefined) node.innerHTML = html;
    return node;
  };
  const esc = (t) => String(t).replace(/[&<>"]/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" }[c]));

  const persons = new Map(F.persons.map((p) => [p.id, p]));
  const places = new Map(F.places.map((p) => [p.id, p]));
  const shortName = (id) => {
    const p = persons.get(id);
    return p ? p.name : id;
  };
  // Canada is drawn east of China so routes cross the Pacific.
  const ll = (place) => [place.lat, place.lng < 0 ? place.lng + 360 : place.lng];

  // A residence covers [from, to); the move year belongs to the new place.
  const lastTo = new Map();
  F.residences.forEach((r) => lastTo.set(r.person, Math.max(lastTo.get(r.person) || 0, r.to)));
  const covers = (r, year) => year >= r.from && (year < r.to || (r.to === lastTo.get(r.person) && year === r.to));

  function whereAt(year) {
    const at = new Map();
    F.residences.forEach((r) => {
      if (covers(r, year)) {
        if (!at.has(r.place)) at.set(r.place, []);
        if (!at.get(r.place).some((x) => x.person === r.person)) at.get(r.place).push(r);
      }
    });
    return at;
  }

  /* ================= Migration model ================= */

  function buildMigration() {
    const range = document.getElementById("year");
    const out = document.getElementById("year-out");
    const panel = document.getElementById("year-panel");
    const legsList = document.getElementById("legs");
    const playBtn = document.getElementById("play");
    const mapEl = document.getElementById("map");
    if (!range || !panel) return;

    let map = null;
    let dynamic = null;
    let scope = "";
    const hasLeaflet = typeof L !== "undefined";

    if (hasLeaflet) {
      map = L.map(mapEl, { scrollWheelZoom: false, zoomSnap: 0.25, worldCopyJump: false, fadeAnimation: false });
      L.tileLayer("https://server.arcgisonline.com/ArcGIS/rest/services/World_Topo_Map/MapServer/tile/{z}/{y}/{x}", {
        attribution: "Tiles &copy; Esri and the GIS User Community",
        maxZoom: 16
      }).addTo(map);
      dynamic = L.layerGroup().addTo(map);
    } else {
      document.getElementById("map-fallback").hidden = false;
    }

    const arc = (a, b, bend = 0.18) => {
      const [lat1, lng1] = a;
      const [lat2, lng2] = b;
      const cLat = (lat1 + lat2) / 2 + (lng2 - lng1) * bend;
      const cLng = (lng1 + lng2) / 2 - (lat2 - lat1) * bend;
      const pts = [];
      for (let t = 0; t <= 1.0001; t += 0.04) {
        const u = 1 - t;
        pts.push([u * u * lat1 + 2 * u * t * cLat + t * t * lat2, u * u * lng1 + 2 * u * t * cLng + t * t * lng2]);
      }
      return pts;
    };

    const moveButtons = F.moves.map((m) => {
      const li = el("li");
      const btn = el("button", "leg",
        `<span class="leg__num" aria-hidden="true">${m.year}</span>` +
        `<span class="leg__title">${esc(m.label)}</span>` +
        `<span class="leg__text">${esc(m.text)}${m.approx ? " Year approx." : ""}</span>`);
      btn.type = "button";
      btn.setAttribute("aria-pressed", "false");
      btn.addEventListener("click", () => {
        stop();
        setYear(m.year);
        range.focus({ preventScroll: true });
      });
      li.appendChild(btn);
      legsList.appendChild(li);
      return [m, btn];
    });

    function render(year) {
      const ink = css("--ink");
      const violet = css("--violet");
      const face = css("--face");
      const at = whereAt(year);

      moveButtons.forEach(([m, b]) => b.setAttribute("aria-pressed", String(m.year === year)));

      // panel
      let html = `<p class="year-panel__year">${year}</p>`;
      if (at.size) {
        html += `<h3>Where everyone was</h3><ul class="where">`;
        [...at.entries()].forEach(([pid, rs]) => {
          const pl = places.get(pid);
          html += `<li><b>${esc(pl.name)}</b> <span class="zh" lang="zh-Hans">${esc(pl.zh)}</span><span>${rs.map((r) => esc(shortName(r.person)) + (r.approx ? "*" : "")).join(", ")}</span></li>`;
        });
        html += "</ul>";
      }
      const offMap = [];
      if (year >= 1951 && year < 1955) offMap.push("Great-grandfather Li: in prison, location not recorded");
      if (year > 1981 && year <= 1995) offMap.push("Great-grandfather Li: later years not recorded");
      if (year > 1966 && year <= 1995) offMap.push("Second daughter Li: married far away, place not recorded");
      if (offMap.length) html += `<p class="where__off">${offMap.map(esc).join("<br>")}</p>`;
      const active = F.events.filter((e) => year >= e.from && year <= e.to);
      if (active.length) {
        html += `<h3>Under way</h3><ul class="happening">`;
        active.forEach((e) => {
          html += `<li class="happening--${e.scope}"><span class="lens">${e.scope === "family" ? "Family" : esc(e.lens[0].toUpperCase() + e.lens.slice(1))}</span><b>${esc(e.label)}</b> ${esc(e.text)}</li>`;
        });
        html += "</ul>";
      }
      if (at.size && [...at.values()].flat().some((r) => r.approx)) html += `<p class="where__off">* Year of residence is approximate.</p>`;
      panel.innerHTML = html;

      if (!map) return;
      dynamic.clearLayers();

      // routes already travelled
      F.moves.filter((m) => m.year <= year).forEach((m) => {
        const recent = year - m.year <= 3;
        L.polyline(arc(ll(places.get(m.from)), ll(places.get(m.to))), {
          color: recent ? violet : ink, weight: recent ? 3.5 : 2, opacity: recent ? 1 : 0.45,
          dashArray: recent ? null : "2 7", lineCap: "round"
        }).addTo(dynamic);
      });

      // occupied places
      at.forEach((rs, pid) => {
        const pl = places.get(pid);
        L.circleMarker(ll(pl), {
          radius: 5 + rs.length * 1.6, color: ink, weight: 2, fillColor: face, fillOpacity: 1
        }).bindTooltip(`${esc(pl.name)} <small>${rs.length}</small>`, {
          permanent: true, direction: "right", offset: [8, 0], className: "place-label"
        }).addTo(dynamic);
      });

      const abroad = [...at.keys()].some((k) => places.get(k).type === "abroad");
      const next = abroad ? "world" : "china";
      if (next !== scope) {
        scope = next;
        const pts = abroad
          ? [ll(places.get("wuhan")), ll(places.get("waterloo")), ll(places.get("montreal"))]
          : [ll(places.get("village")), ll(places.get("wuhan")), ll(places.get("changsha"))];
        const first = !map._loaded;
        if (first || reduceMotion) map.fitBounds(L.latLngBounds(pts), { padding: [60, 60], maxZoom: 7, animate: false });
        else map.flyToBounds(L.latLngBounds(pts), { padding: [60, 60], maxZoom: 7, duration: 0.9 });
      }
    }

    function setYear(y) {
      const year = Math.max(1910, Math.min(2026, Math.round(y)));
      range.value = year;
      out.value = year;
      out.textContent = year;
      render(year);
    }

    let timer = null;
    function stop() {
      if (timer) clearInterval(timer);
      timer = null;
      playBtn.textContent = "Play";
      playBtn.setAttribute("aria-pressed", "false");
    }
    playBtn.addEventListener("click", () => {
      if (timer) return stop();
      if (+range.value >= 2026) setYear(1910);
      playBtn.textContent = "Pause";
      playBtn.setAttribute("aria-pressed", "true");
      timer = setInterval(() => {
        const y = +range.value + 1;
        setYear(y);
        if (y >= 2026) stop();
      }, reduceMotion ? 260 : 140);
    });
    range.addEventListener("input", () => {
      stop();
      setYear(+range.value);
    });

    setYear(+range.value);
  }

  /* ================= Network ================= */

  const contextLinks = [
    ["f1951", "e1950"], ["f1951", "e1950b"], ["f1945a", "e1937"], ["f1945a", "e1945"], ["f1959", "e1953"], ["f1963", "e1966"], ["f1981", "e1982"], ["f1982", "e1982"], ["f2000", "e1978"], ["f2000", "e1998"], ["e1958", "villagecom"]
  ];

  function buildNetwork() {
    const host = document.getElementById("graph");
    const detail = document.getElementById("graph-detail");
    if (!host || typeof d3 === "undefined") return;

    const nodes = [];
    const add = (id, label, kind, info) => nodes.push({ id, label, kind, info });
    F.persons.forEach((p) => add(p.id, p.name, "person", [p.role, p.education, p.occupation].filter(Boolean).join(". ")));
    F.places.forEach((p) => add(p.id, p.name, "place", p.approx ? "Position approximate." : p.type));
    F.groups.forEach((g) => add(g.id, g.name, "group", g.text));
    const usedNational = new Set(contextLinks.flat());
    F.events.forEach((e) => {
      if (e.scope === "family" && e.persons && e.persons.length && !/born$/.test(e.label)) add(e.id, e.label, "event", e.text);
      if (e.scope === "national" && usedNational.has(e.id)) add(e.id, e.label, "national", e.text);
    });
    const ids = new Set(nodes.map((n) => n.id));

    const links = [];
    const link = (s, t, type) => { if (ids.has(s) && ids.has(t)) links.push({ source: s, target: t, type }); };
    F.relations.forEach((r) => link(r.source, r.target, r.type));
    const lived = new Set();
    F.residences.forEach((r) => {
      const k = r.person + ">" + r.place;
      if (!lived.has(k)) { lived.add(k); link(r.person, r.place, "lived in"); }
    });
    F.events.forEach((e) => (e.persons || []).forEach((p) => link(p, e.id, "experienced")));
    contextLinks.forEach(([a, b]) => link(a, b, "part of"));

    const width = Math.max(host.clientWidth || 800, 720);
    const height = 760;
    const sim = d3.forceSimulation(nodes)
      .force("link", d3.forceLink(links).id((d) => d.id).distance((l) => (l.type === "parent" ? 80 : 120)).strength(0.4))
      .force("charge", d3.forceManyBody().strength(-480))
      .force("center", d3.forceCenter(width / 2, height / 2))
      .force("collide", d3.forceCollide(width < 600 ? 24 : 40))
      .force("x", d3.forceX(width / 2).strength(width < 600 ? 0.06 : 0.02))
      .force("y", d3.forceY(height / 2).strength(width < 600 ? 0.1 : 0.05))
      .stop();
    const clamp = () => nodes.forEach((n) => {
      n.x = Math.max(30, Math.min(width - 150, n.x));
      n.y = Math.max(24, Math.min(height - 24, n.y));
    });
    for (let i = 0; i < 400; i++) { sim.tick(); clamp(); }

    const svg = d3.select(host).append("svg").attr("viewBox", `0 0 ${width} ${height}`).attr("width", width).attr("height", height);
    const linkSel = svg.append("g").attr("class", "g-links").selectAll("line").data(links).join("line")
      .attr("x1", (d) => d.source.x).attr("y1", (d) => d.source.y).attr("x2", (d) => d.target.x).attr("y2", (d) => d.target.y)
      .attr("class", (d) => "g-link g-link--" + d.type.replace(/\s/g, "-"));

    const symbol = { person: d3.symbolCircle, place: d3.symbolSquare, group: d3.symbolTriangle, event: d3.symbolDiamond, national: d3.symbolDiamond };
    const size = { person: 300, place: 220, group: 240, event: 170, national: 170 };

    const nodeSel = svg.append("g").selectAll("g").data(nodes).join("g")
      .attr("class", (d) => "g-node g-node--" + d.kind)
      .attr("transform", (d) => `translate(${d.x},${d.y})`)
      .attr("tabindex", 0).attr("role", "button")
      .attr("aria-label", (d) => `${d.label}, ${d.kind === "national" ? "national event" : d.kind}`);
    nodeSel.append("title").text((d) => d.label);
    nodeSel.append("circle").attr("r", 22).attr("class", "g-hit");
    nodeSel.append("path").attr("d", (d) => d3.symbol(symbol[d.kind], size[d.kind])());
    nodeSel.append("text").attr("x", 12).attr("y", 4).text((d) => d.label)
      .attr("class", (d) => (d.kind === "person" || d.kind === "place" ? "g-label" : "g-label g-label--minor"));

    const neighbours = (id) => {
      const set = new Set([id]);
      links.forEach((l) => {
        if (l.source.id === id) set.add(l.target.id);
        if (l.target.id === id) set.add(l.source.id);
      });
      return set;
    };

    function select(d) {
      const near = neighbours(d.id);
      nodeSel.classed("is-dim", (n) => !near.has(n.id)).classed("is-near", (n) => near.has(n.id)).classed("is-on", (n) => n.id === d.id);
      linkSel.classed("is-dim", (l) => l.source.id !== d.id && l.target.id !== d.id);
      const rows = links.filter((l) => l.source.id === d.id || l.target.id === d.id)
        .map((l) => {
          const other = l.source.id === d.id ? l.target : l.source;
          const verb = l.source.id === d.id ? l.type : ({ "cut off contact": "contact cut off by", parent: "child of", member: "includes", studied: "attended by", worked: "workplace of", "lived in": "home of", experienced: "involved", "part of": "context for" }[l.type] || l.type);
          return `<li><span>${esc(verb)}</span> ${esc(other.label)}</li>`;
        }).join("");
      detail.innerHTML = `<p class="graph-detail__name">${esc(d.label)}</p><p>${esc(d.info || "")}</p><ul>${rows}</ul>`;
    }
    nodeSel.on("click", (e, d) => select(d)).on("keydown", (e, d) => {
      if (e.key === "Enter" || e.key === " ") { e.preventDefault(); select(d); }
    });
    svg.on("click", (e) => {
      if (e.target === svg.node()) {
        nodeSel.classed("is-dim", false).classed("is-on", false).classed("is-near", false);
        linkSel.classed("is-dim", false);
      }
    });

    const legend = document.getElementById("graph-legend");
    [["person", "Person"], ["place", "Place"], ["group", "Community or institution"], ["event", "Family event"], ["national", "National event"]].forEach(([k, label]) => {
      const li = el("li", "legend__item legend__item--" + k);
      li.innerHTML = `<svg width="18" height="18" viewBox="-9 -9 18 18" aria-hidden="true"><path d="${d3.symbol(symbol[k], size[k] * 0.55)()}"/></svg>${label}`;
      legend.appendChild(li);
    });
    [["parent", "Parent and child"], ["cut", "Contact cut off, 1963 to 1981"]].forEach(([k, label]) => {
      legend.appendChild(el("li", "legend__item legend__edge legend__edge--" + k, `<i aria-hidden="true"></i>${label}`));
    });

    const table = document.getElementById("graph-table");
    table.innerHTML = "<thead><tr><th scope=\"col\">From</th><th scope=\"col\">Connection</th><th scope=\"col\">To</th></tr></thead><tbody>" +
      links.map((l) => `<tr><td>${esc(l.source.label)}</td><td>${esc(l.type)}</td><td>${esc(l.target.label)}</td></tr>`).join("") + "</tbody>";
  }

  /* ================= National change vs the family ================= */

  const COHORT = ["zhiyuan", "zhiqing", "zhiping", "zhilan", "zhikang", "zhimei"];

  // Share of the six surviving children living in a town or city, 1950-1995.
  function familyUrbanShare() {
    const rows = [];
    for (let y = 1950; y <= 1995; y++) {
      let urban = 0;
      COHORT.forEach((pid) => {
        const r = F.residences.find((x) => x.person === pid && covers(x, y));
        if (r && places.get(r.place).type !== "village") urban += 1;
      });
      rows.push([y, Math.round((urban / COHORT.length) * 1000) / 10, urban]);
    }
    return rows;
  }

  function buildMacro() {
    const host = document.getElementById("macro-chart");
    if (!host || typeof d3 === "undefined") return;

    const fam = familyUrbanShare();
    const series = [
      { key: "urban", label: "China: urban population", data: F.macro.urban_share, cls: "s-urban" },
      { key: "farm", label: "China: jobs in farming", data: F.macro.primary_employment_share, cls: "s-farm" },
      { key: "family", label: "Li siblings: how many of the six lived in a town or city", data: fam.map(([y, v]) => [y, v]), cls: "s-family", step: true }
    ];

    const width = Math.max(host.clientWidth, 320);
    const narrow = width < 640;
    const height = narrow ? 320 : 400;
    const m = { top: 20, right: narrow ? 16 : 190, bottom: 36, left: 44 };
    const x = d3.scaleLinear().domain([1945, 2026]).range([m.left, width - m.right]);
    const y = d3.scaleLinear().domain([0, 100]).range([height - m.bottom, m.top]);

    const svg = d3.select(host).append("svg").attr("viewBox", `0 0 ${width} ${height}`).attr("width", "100%").attr("height", height)
      .attr("role", "img").attr("aria-label", "Line chart comparing China's urban share and farm employment with the Li family's urban share, 1945 to 2026. The table below has the values.");

    svg.append("g").attr("class", "axis axis--y").attr("transform", `translate(${m.left},0)`)
      .call(d3.axisLeft(y).ticks(5).tickSize(-(width - m.left - m.right)).tickFormat((d) => d + "%"))
      .call((g) => g.select(".domain").remove());
    svg.append("g").attr("class", "axis axis--x").attr("transform", `translate(0,${height - m.bottom})`)
      .call(d3.axisBottom(x).ticks(narrow ? 5 : 9).tickFormat(d3.format("d")).tickSize(0).tickPadding(10))
      .call((g) => g.select(".domain").remove());

    // family events as quiet reference ticks
    [[1950, "Land reform"], [1958, "Hukou rules"], [1978, "Reform"], [1998, "Housing reform"]].forEach(([yr, label]) => {
      svg.append("line").attr("class", "macro__event").attr("x1", x(yr)).attr("x2", x(yr)).attr("y1", m.top).attr("y2", height - m.bottom);
      if (!narrow) svg.append("text").attr("class", "macro__event-label").attr("x", x(yr) + 4).attr("y", m.top + 10).text(label);
    });

    series.forEach((s) => {
      const line = d3.line().x((d) => x(d[0])).y((d) => y(d[1]));
      if (s.step) line.curve(d3.curveStepAfter);
      svg.append("path").attr("class", "macro__line " + s.cls).attr("d", line(s.data));
      if (!s.step) svg.append("g").selectAll("circle").data(s.data).join("circle")
        .attr("class", "macro__dot " + s.cls).attr("cx", (d) => x(d[0])).attr("cy", (d) => y(d[1])).attr("r", 4);
      if (!narrow) {
        const last = s.data[s.data.length - 1];
        const dy = s.key === "urban" ? -6 : s.key === "farm" ? 14 : 4;
        svg.append("text").attr("class", "macro__end " + s.cls).attr("x", x(last[0]) + 8).attr("y", y(last[1]) + dy)
          .text(s.key === "family" ? "Li siblings" : s.key === "urban" ? "China: urban" : "China: farm jobs");
      }
    });

    const legend = el("ul", "legend");
    series.forEach((s) => legend.appendChild(el("li", "legend__item legend__line " + s.cls, `<i aria-hidden="true"></i>${esc(s.label)}`)));
    host.prepend(legend);

    const interp = (data, yr) => {
      if (yr < data[0][0] || yr > data[data.length - 1][0]) return null;
      for (let i = 0; i < data.length - 1; i++) {
        const [x0, v0] = data[i];
        const [x1, v1] = data[i + 1];
        if (yr >= x0 && yr <= x1) return { v: v0 + ((v1 - v0) * (yr - x0)) / (x1 - x0), exact: yr === x0 || yr === x1 };
      }
      return { v: data[data.length - 1][1], exact: true };
    };

    // the years the sibling line steps up, and who moved
    const steps = fam.filter(([yr, , n], i) => i > 0 && n !== fam[i - 1][2]).map(([yr, v, n]) => {
      const movers = F.residences.filter((r) => COHORT.includes(r.person) && r.from === yr && places.get(r.place).type !== "village");
      return { yr, v, n, movers, approx: movers.some((r) => r.approx) };
    });
    steps.forEach((s) => {
      svg.append("circle").attr("class", "macro__step").attr("cx", x(s.yr)).attr("cy", y(s.v)).attr("r", 4.5);
      svg.append("text").attr("class", "macro__step-label").attr("x", x(s.yr) + 7).attr("y", y(s.v) - 8).text(`${s.n} of 6`);
    });

    const read = document.getElementById("macro-read");
    if (read) {
      const pct = (v) => Math.round(v) + "%";
      const who = (rs) => {
        const names = rs.map((r) => shortName(r.person));
        const list = names.length > 1 ? names.slice(0, -1).join(", ") + " and " + names[names.length - 1] : names[0];
        return `${list} ${names.length > 1 ? "move" : "moves"} to ${places.get(rs[0].place).name.replace(/^Local town$/, "the local town")}`;
      };
      const lastStep = steps[steps.length - 1];
      const nat = lastStep && interp(F.macro.urban_share, lastStep.yr);
      read.innerHTML =
        `<h3>How to read the purple line</h3>` +
        `<div class="macro-read__cols"><div class="prose">` +
        `<p>The six are my great-grandfather’s children who survived childhood: my grandfather and his five brothers and sisters. For each year, the line counts how many of the six lived in a town or city rather than in the home village, and shows that as a share of six. Two of six is 33%.</p>` +
        `<p>It moves in steps because it only changes when one of them moves. Children not yet born, and the second daughter after she married to a place the account does not record, count as not in a town.</p>` +
        (nat ? `<p>Set against the solid line for China’s urban population, the family was ahead of the country: by ${lastStep.yr}, ${["no one", "one", "two", "three", "four", "five", "all"][lastStep.n]} of the six lived in a town, ${pct(lastStep.v)}, when China as a whole was about ${pct(nat.v)} urban. The difference came from education and, later, from the return of property that let the family move into town.</p>` : "") +
        `</div><ol class="macro-read__steps">` +
        steps.map((s) => `<li><b>${s.yr}${s.approx ? " approx." : ""}</b><span class="macro-read__n">${s.n} of 6, ${pct(s.v)}</span><span>${esc(who(s.movers))}.</span></li>`).join("") +
        `</ol></div>`;
    }

    // hover and keyboard crosshair
    const famAt = new Map(fam.map(([yr, v, n]) => [yr, [v, n]]));
    const cross = svg.append("line").attr("class", "macro__cross").attr("y1", m.top).attr("y2", height - m.bottom).style("opacity", 0);
    const tip = el("div", "tooltip");
    tip.hidden = true;
    host.appendChild(tip);

    function show(yr) {
      yr = Math.max(1945, Math.min(2026, Math.round(yr)));
      cross.attr("x1", x(yr)).attr("x2", x(yr)).style("opacity", 1);
      const u = interp(F.macro.urban_share, yr);
      const f = interp(F.macro.primary_employment_share, yr);
      const fm = famAt.get(yr);
      tip.innerHTML = `<b>${yr}</b>` +
        (u ? `<span><i class="s-urban"></i>China urban ${u.exact ? "" : "≈"}${u.v.toFixed(1)}%</span>` : "") +
        (f ? `<span><i class="s-farm"></i>China farm jobs ${f.exact ? "" : "≈"}${f.v.toFixed(1)}%</span>` : "") +
        (fm ? `<span><i class="s-family"></i>Li siblings ${fm[0]}% (${fm[1]} of 6)</span>` : "");
      tip.hidden = false;
      const left = Math.min(x(yr) / width * host.clientWidth + 12, host.clientWidth - 230);
      tip.style.left = Math.max(0, left) + "px";
      tip.style.top = "56px";
      svg.attr("data-year", yr);
    }
    const hide = () => { cross.style("opacity", 0); tip.hidden = true; };
    svg.on("pointermove", (e) => {
      const [px] = d3.pointer(e);
      show(x.invert(px));
    }).on("pointerleave", hide);
    svg.attr("tabindex", 0).on("keydown", (e) => {
      const cur = +svg.attr("data-year") || 1978;
      if (e.key === "ArrowRight") { e.preventDefault(); show(cur + 1); }
      if (e.key === "ArrowLeft") { e.preventDefault(); show(cur - 1); }
    }).on("focus", () => show(+svg.attr("data-year") || 1978)).on("blur", hide);

    const table = document.getElementById("macro-table");
    const years = [1949, 1952, 1955, 1956, 1960, 1978, 1982, 1990, 2000, 2010, 2020];
    const val = (data, yr) => { const hit = data.find((d) => d[0] === yr); return hit ? hit[1] + "%" : ""; };
    table.innerHTML = `<thead><tr><th scope="col">Year</th><th scope="col">China urban population</th><th scope="col">China jobs in farming</th><th scope="col">Li siblings in a town or city</th></tr></thead><tbody>` +
      years.map((yr) => `<tr><td>${yr}</td><td>${val(F.macro.urban_share, yr)}</td><td>${val(F.macro.primary_employment_share, yr)}</td><td>${famAt.has(yr) ? famAt.get(yr)[0] + "% (" + famAt.get(yr)[1] + " of 6)" : ""}</td></tr>`).join("") + "</tbody>";
  }

  /* ================= Keyword mining ================= */

  function buildMined() {
    const host = document.getElementById("mined");
    if (!host || !M) return;
    const gens = Object.keys(M.generations);
    const tabs = document.getElementById("mined-tabs");
    const meta = document.getElementById("mined-meta");
    const zhGen = { g2: "第二代", g3: "第三代", g4: "第四代" };

    meta.textContent = `Corpus: ${M.corpus_label}. ` + gens.map((g) => { const G = M.generations[g]; return G.words ? `${G.label} about ${G.words.toLocaleString("en")} words` : `${G.label} ${G.characters.toLocaleString("en")} characters`; }).join(", ") + `. Method: ${M.method}.`;

    function render(gid) {
      const info = M.generations[gid];
      [...tabs.querySelectorAll("button")].forEach((b) => b.setAttribute("aria-selected", String(b.dataset.gen === gid)));
      const max = Math.max(1, ...M.dimensions.flatMap((d) => d.codes[gid].map((r) => r.count)));
      host.innerHTML = "";
      host.setAttribute("aria-label", `${info.label}: keyword counts by dimension`);
      M.dimensions.forEach((d) => {
        const col = el("div", "key-col");
        const total = d.codes[gid].reduce((sum, r) => sum + r.count, 0);
        col.appendChild(el("h3", "", `${esc(d.label)} <span class="zh" lang="zh-Hans">${esc(d.zh)}</span><small>${esc(d.question)} ${total} matches.</small>`));
        const ol = el("ol", "key-list");
        [...d.codes[gid]].sort((x, y) => y.count - x.count).forEach((r) => {
          const li = el("li", "key-row" + (r.count ? "" : " key-row--zero"));
          li.tabIndex = 0;
          li.title = `${r.count} occurrences, ${r.per10k} per 10,000 tokens`;
          li.setAttribute("aria-label", `${r.term}, ${r.en}: ${r.count} occurrences`);
          li.innerHTML =
            `<span class="key-term"><span class="zh" lang="zh-Hans">${esc(r.term)}</span><span class="key-en">${esc(r.en)}</span></span>` +
            `<span class="key-bar"><i style="width:${(r.count / max) * 100}%"></i><b>${r.count}</b></span>`;
          ol.appendChild(li);
        });
        col.appendChild(ol);
        host.appendChild(col);
      });
    }

    gens.forEach((g) => {
      const info = M.generations[g];
      const b = el("button", "tab", `${esc(info.label)} <span lang="zh-Hans">${zhGen[g] || ""}</span>`);
      b.type = "button";
      b.setAttribute("role", "tab");
      b.dataset.gen = g;
      b.addEventListener("click", () => render(g));
      b.addEventListener("keydown", (e) => {
        if (e.key !== "ArrowRight" && e.key !== "ArrowLeft") return;
        const list = [...tabs.querySelectorAll("button")];
        const next = list[(list.indexOf(b) + (e.key === "ArrowRight" ? 1 : list.length - 1)) % list.length];
        next.focus();
        render(next.dataset.gen);
      });
      tabs.appendChild(b);
    });
    render(gens[0]);
  }

  /* ================= Themes across generations ================= */

  function themeTable() {
    const gens = Object.keys(M.generations);
    return (M.themes || []).map((t) => {
      const cells = gens.map((gid) => {
        const counts = new Map();
        M.dimensions.forEach((d) => (d.codes[gid] || []).forEach((r) => counts.set(r.term, Math.max(counts.get(r.term) || 0, r.count))));
        const terms = t.terms.filter((term) => counts.has(term)).map((term) => [term, counts.get(term)]).sort((a, b) => b[1] - a[1]);
        if (!terms.length) return { gid, absent: true };
        const G = M.generations[gid];
        const size = G.words || G.tokens || G.characters || 1;
        const count = terms.reduce((s, [, c]) => s + c, 0);
        return { gid, count, rate: (count / size) * 10000, terms };
      });
      return { ...t, cells };
    });
  }

  function buildShift() {
    const host = document.getElementById("shift-chart");
    const detail = document.getElementById("shift-detail");
    const list = document.getElementById("shift-themes");
    if (!host || !M || !M.themes || !M.themes.length || typeof d3 === "undefined") return;

    const gens = Object.keys(M.generations);
    const born = { g2: "born 1939", g3: "born 1973", g4: "born 2000s" };
    const themes = themeTable();

    // rank within each generation; absent themes go below the ranked ones
    const slot = new Map();
    const ranked = {};
    gens.forEach((gid, gi) => {
      const present = themes.filter((t) => !t.cells[gi].absent).sort((a, b) => b.cells[gi].rate - a.cells[gi].rate);
      const absent = themes.filter((t) => t.cells[gi].absent);
      ranked[gid] = present.length;
      present.forEach((t, i) => { t.cells[gi].rank = i + 1; slot.set(t.id + gi, i); });
      absent.forEach((t, i) => slot.set(t.id + gi, present.length + i));
    });

    const W = 760;
    const rowH = 40;
    const top = 70;
    const H = top + themes.length * rowH + 8;
    const colX = gens.map((_, i) => 215 + i * 165);
    const yAt = (t, gi) => top + slot.get(t.id + gi) * rowH + rowH / 2;

    const svg = d3.select(host).append("svg").attr("viewBox", `0 0 ${W} ${H}`).attr("width", W).attr("height", H)
      .attr("role", "img").attr("aria-label", "Ranking of ten themes in generations 2, 3 and 4. The theme buttons above and the table below give the same information.");

    gens.forEach((gid, gi) => {
      const g = svg.append("g").attr("class", "shift__col");
      g.append("text").attr("class", "shift__col-title").attr("x", colX[gi]).attr("y", 24).text(M.generations[gid].label);
      g.append("text").attr("class", "shift__col-sub").attr("x", colX[gi]).attr("y", 44).text(born[gid] || "");
      g.append("line").attr("class", "shift__col-rule").attr("x1", colX[gi]).attr("x2", colX[gi]).attr("y1", top - 6).attr("y2", H - 4);
    });

    const curve = (x1, y1, x2, y2) => `M${x1},${y1} C${(x1 + x2) / 2},${y1} ${(x1 + x2) / 2},${y2} ${x2},${y2}`;
    const groups = svg.append("g").selectAll("g").data(themes).join("g").attr("class", "shift__theme").attr("data-id", (t) => t.id);

    groups.each(function (t) {
      const g = d3.select(this);
      for (let gi = 0; gi < gens.length - 1; gi++) {
        const faint = t.cells[gi].absent || t.cells[gi + 1].absent;
        const d = curve(colX[gi], yAt(t, gi), colX[gi + 1], yAt(t, gi + 1));
        g.append("path").attr("class", "shift__hit").attr("d", d);
        g.append("path").attr("class", "shift__seg" + (faint ? " is-faint" : "")).attr("d", d);
      }
      t.cells.forEach((c, gi) => {
        if (c.absent) {
          g.append("circle").attr("class", "shift__gap").attr("cx", colX[gi]).attr("cy", yAt(t, gi)).attr("r", 5);
        } else {
          g.append("circle").attr("class", "shift__node").attr("cx", colX[gi]).attr("cy", yAt(t, gi)).attr("r", 14);
          g.append("text").attr("class", "shift__rank").attr("x", colX[gi]).attr("y", yAt(t, gi) + 5).text(c.rank);
        }
      });
      g.append("text").attr("class", "shift__label shift__label--l").attr("x", colX[0] - 24).attr("y", yAt(t, 0) + 5).text(t.label);
      g.append("text").attr("class", "shift__label shift__label--r").attr("x", colX[gens.length - 1] + 24).attr("y", yAt(t, gens.length - 1) + 5).text(t.label);    });

    const seq = (t) => t.cells.map((c) => (c.absent ? "–" : c.rank)).join(" · ");
    const buttons = themes.map((t) => {
      const b = el("button", "shift__btn", `<span>${esc(t.label)}</span><small aria-hidden="true">${seq(t)}</small>`);
      b.type = "button";
      b.setAttribute("aria-pressed", "false");
      b.setAttribute("aria-label", `${t.label}: ` + t.cells.map((c, gi) => `${M.generations[gens[gi]].label} ${c.absent ? "not among keywords" : "rank " + c.rank}`).join(", "));
      b.addEventListener("click", () => select(t.id));
      list.appendChild(b);
      return [t.id, b];
    });

    let current = null;
    function highlight(id) {
      groups.classed("is-on", (t) => t.id === id).classed("is-off", (t) => id && t.id !== id);
      groups.filter((t) => t.id === id).raise();
    }
    function select(id) {
      current = id;
      highlight(id);
      buttons.forEach(([bid, b]) => b.setAttribute("aria-pressed", String(bid === id)));
      const t = themes.find((x) => x.id === id);
      detail.innerHTML =
        `<p class="shift__detail-name">${esc(t.label)} <span class="zh" lang="zh-Hans">${esc(t.zh)}</span></p>` +
        `<ol class="shift__gens">` + t.cells.map((c, gi) => {
          const gid = gens[gi];
          const head = `<b>${esc(M.generations[gid].label)}</b> <span>${born[gid] || ""}</span>`;
          if (c.absent) return `<li class="is-absent">${head}<p>Not among this generation’s keywords.</p></li>`;
          return `<li>${head}<p><strong>#${c.rank} of ${ranked[gid]}</strong> · ${c.rate.toFixed(0)} per 10,000 words</p>` +
            `<p class="shift__terms">${c.terms.slice(0, 5).map(([term, n]) => `<span lang="zh-Hans">${esc(term)}</span> ${n}`).join(" · ")}</p></li>`;
        }).join("") + `</ol><p class="shift__note">${esc(t.note || "")}</p>`;
    }

    groups.on("pointerenter", (e, t) => highlight(t.id)).on("pointerleave", () => highlight(current)).on("click", (e, t) => select(t.id));

    // start with the theme that fell furthest
    const pos = (t, gi) => (t.cells[gi].absent ? themes.length + 1 : t.cells[gi].rank);
    const fell = [...themes].sort((a, b) => (pos(b, gens.length - 1) - pos(b, 0)) - (pos(a, gens.length - 1) - pos(a, 0)))[0];
    select(fell.id);

    document.getElementById("shift-note").textContent =
      `${M.themes_note || ""} Ranks use counts per 10,000 words, so a generation with longer interviews does not score higher just for talking more. A hollow dot means that generation’s codebook has none of the theme’s words, so the theme was not counted there.`;

    const table = document.getElementById("shift-table");
    table.innerHTML = `<thead><tr><th scope="col">Theme</th>${gens.map((gid) => `<th scope="col">${esc(M.generations[gid].label)}</th>`).join("")}</tr></thead><tbody>` +
      themes.map((t) => `<tr><td>${esc(t.label)}</td>${t.cells.map((c) => `<td>${c.absent ? "not counted" : `#${c.rank}, ${c.rate.toFixed(0)} per 10,000 words`}</td>`).join("")}</tr>`).join("") + "</tbody>";
  }

  /* ================= Keyword marking demo ================= */

  const EXAMPLES = {
    g2: "1951年土地改革，家里被划成地主成分，房子和田地都没收了。那年我离开桃源，去常德读书，1955年考上武汉的大学，学建筑工程，毕业后分到鄂州的工厂。",
    g3: "我们1973年在鄂州出生，赶上改革开放，高考之后上了大学。1991年搬到武汉，进了单位，最在意的是工作稳定、收入和买房。",
    g4: "我们这一代从小就在竞争和内卷里长大，压力很大。我2022年出国留学，先到蒙特利尔，后来去滑铁卢读大学，常常想未来的就业和身份。",
    en: "Land reform came in 1951. The property was confiscated and the family fell into hardship. My grandfather left Taoyuan for school in Changde, went to university in Wuhan, and later moved to Ezhou to work at a factory."
  };

  // Extra English forms for codebook terms, keyed by the Chinese term.
  const EN_EXTRA = {
    "战争": ["wars", "wartime"], "逃难": ["flee", "fled", "fleeing", "refugee", "refugees"], "地主": ["landlords"],
    "没收": ["confiscated", "confiscate"], "破产": ["bankrupt"], "困难": ["hardships", "difficulties", "poor", "poverty"],
    "读书": ["study", "studied", "studies"], "学习": ["learn", "learned", "learnt"], "大学": ["college", "colleges", "universities"],
    "学校": ["schools"], "考试": ["exam"], "工作": ["job", "jobs", "career", "worked", "working", "business"], "工程": ["engineer", "engineers"],
    "教育": ["educated"], "城市": ["cities", "urban"], "留学": ["study abroad", "studied abroad"], "出国": ["abroad", "go abroad", "went abroad"],
    "海外": ["overseas"], "美国": ["US", "U.S.", "America", "American"], "加拿大": ["Canadian"],
    "移民": ["immigration", "immigrate", "emigrate", "emigrated"], "竞争": ["compete", "competitive"], "压力": ["stress", "stressed"],
    "焦虑": ["anxious"], "就业": ["employed"], "实习": ["intern", "interns"], "申请": ["apply", "applied", "application"],
    "成绩": ["grade", "score", "scores"], "专业": ["majors"], "房贷": ["mortgages"], "买房": ["buy a home", "bought a home", "buy a house", "bought a house"],
    "房子": ["house", "houses", "apartment", "home"], "住房": ["housing"], "工资": ["salary", "salaries", "wage"], "收入": ["money", "earn", "earned", "earning"],
    "稳定": ["stable", "security"], "失业": ["unemployed", "jobless", "laid off"], "养老": ["retirement", "pension"], "解放": ["liberated"],
    "改革开放": ["reform and opening up"], "城市化": ["urbanisation"], "全球化": ["globalisation", "global"], "疫情": ["covid", "covid-19"],
    "科技": ["tech"], "互联网": ["online"], "发展": ["develop", "growth"], "机会": ["opportunities", "chance", "chances"],
    "定居": ["settle", "settled"], "搬家": ["move", "moved", "moving", "moves", "relocated"],
    "农村": ["rural", "village", "countryside"], "老家": ["hometown"], "离开": ["leave", "left"], "联系": ["contact", "in touch"]
  };

  // Everyday Chinese variants of codebook terms. The published counts use the codebook terms only.
  const ZH_VARIANTS = {
    "搬家": ["搬到", "搬去", "搬来", "搬迁", "迁到", "迁往", "迁居", "移居"],
    "离开": ["离家", "走出"],
    "城市": ["城里", "进城", "大城市"],
    "农村": ["乡下", "村里", "乡村"],
    "家乡": ["故乡"],
    "工作": ["上班", "打工", "做生意", "经商", "下海", "创业"],
    "收入": ["赚钱", "挣钱", "赚到", "挣到", "第一桶金"],
    "工资": ["薪水", "工钱"],
    "失业": ["下岗"],
    "单位": ["国企"],
    "读书": ["上学", "念书"],
    "学校": ["私塾", "中学", "小学"],
    "困难": ["艰难", "贫困", "吃苦", "苦日子"],
    "战争": ["打仗"],
    "逃难": ["逃到", "逃往"],
    "联系": ["来往", "通信", "写信"],
    "断绝联系": ["断了联系", "断绝来往"],
    "出国": ["国外"],
    "机会": ["机遇"],
    "稳定": ["铁饭碗", "安稳"],
    "买房": ["买了房"],
    "改革开放": ["改开"]
  };

  // Place names count toward Migration, as place names in the codebook do.
  const ZH_PLACES = "北方 南方 东北 西北 沿海 外地 广东 广州 深圳 上海 北京 天津 重庆 南京 杭州 苏州 厦门 成都 西安 郑州 香港 台湾 湖南 湖北 河南 四川 浙江 江苏 福建 海南 黄石 岳阳 株洲 蒙特利尔 斯坦斯特德 滑铁卢 多伦多 温哥华 英国 澳大利亚 日本 新加坡".split(" ");
  const EN_PLACES = "Guangdong|Guangzhou|Shenzhen|Shanghai|Beijing|Hunan|Hubei|Changsha|Taoyuan|Changde|Cili|Ezhou|Wuhan|Montreal|Stanstead|Waterloo|Toronto|Vancouver|Ontario|Quebec|Canada|Britain|England|Australia|Japan|Singapore|Hong Kong".split("|");

  const ZH_STOP = new Set("之后 之前 以后 以前 后来 当时 那时 那年 我们 他们 你们 她们 自己 大家 这个 那个 一个 一些 这些 那些 这样 那样 这种 那种 已经 因为 所以 但是 可是 然后 就是 还是 也是 不是 可以 没有 什么 怎么 时候 现在 开始 觉得 知道 非常 很多 一直 为了 关于 以及 或者 而且 如果 虽然 只是 其实 比较 一样 的话 起来 出来 进行 这一 一代 都是 从小".split(" "));
  const EN_STOP = new Set("the and for with that this from was were are have has had they them their our his her its into about after before then than when what which who will would could should there here also just very many much some more most such only other over under again been being did does doing each few how why all any both not nor own same too can out off down one two year years later fell came went got made make like".split(" "));

  function buildDemo() {
    const input = document.getElementById("demo-text");
    const marked = document.getElementById("demo-marked");
    const unknownEl = document.getElementById("demo-unknown");
    const countsEl = document.getElementById("demo-counts");
    if (!input || !M) return;

    const dims = M.dimensions.map((d) => ({ id: d.id, label: d.label, zh: d.zh }));
    const dimLabel = (id) => dims.find((d) => d.id === id).label;
    const isZh = (t) => /[^\x00-\x7f]/.test(t);

    // lexicon: surface form -> { dims, term, kind }
    const lex = new Map();
    const add = (form, dimIds, term, kind) => {
      const key = isZh(form) ? form : form.toLowerCase();
      if (!key) return;
      if (!lex.has(key)) lex.set(key, { dims: new Set(), term, kind });
      dimIds.forEach((id) => lex.get(key).dims.add(id));
    };
    const codeDims = new Map();
    M.dimensions.forEach((d) => Object.values(d.codes).forEach((rows) => rows.forEach((r) => r.term.split("/").forEach((t) => {
      if (!codeDims.has(t)) codeDims.set(t, new Set());
      codeDims.get(t).add(d.id);
    }))));
    const englishForms = (gloss) => gloss.split(/,\s*|\s+or\s+/).map((x) => x.trim().replace(/^(the|a|an)\s+/i, "")).filter(Boolean);
    M.dimensions.forEach((d) => Object.values(d.codes).forEach((rows) => rows.forEach((r) => {
      r.term.split("/").forEach((t) => {
        add(t, codeDims.get(t), t, "code");
        (EN_EXTRA[t] || []).forEach((e) => add(e, codeDims.get(t), t, "variant"));
      });
      englishForms(r.en).forEach((e) => add(e, codeDims.get(r.term.split("/")[0]), r.term, "variant"));
    })));
    Object.entries(ZH_VARIANTS).forEach(([term, forms]) => {
      if (codeDims.has(term)) forms.forEach((f) => { if (!lex.has(f)) add(f, codeDims.get(term), term, "variant"); });
    });
    [...ZH_PLACES, ...EN_PLACES].forEach((p) => { if (!lex.has(isZh(p) ? p : p.toLowerCase())) add(p, ["migration"], null, "place"); });
    const custom = new Map();

    const escRe = (x) => x.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
    const byLen = (a, b) => b.length - a.length;
    let matcher;
    const compile = () => {
      const keys = [...lex.keys(), ...custom.keys()];
      const en = keys.filter((k) => !isZh(k)).sort(byLen).map(escRe).join("|");
      const zh = keys.filter(isZh).sort(byLen).map(escRe).join("|");
      matcher = new RegExp(`(\\b(?:${en})(?:es|s)?\\b)|(${zh})`, "gi");
    };
    compile();

    const entryFor = (hit) => {
      if (isZh(hit)) return custom.get(hit) || lex.get(hit);
      const low = hit.toLowerCase();
      for (const k of [low, low.replace(/es$/, ""), low.replace(/s$/, "")]) {
        if (custom.has(k)) return custom.get(k);
        if (lex.has(k)) return lex.get(k);
      }
      return null;
    };

    const segmenter = typeof Intl !== "undefined" && Intl.Segmenter ? new Intl.Segmenter("zh", { granularity: "word" }) : null;
    const segment = (text) => (segmenter ? [...segmenter.segment(text)] : [{ segment: text, isWordLike: false }]);

    let pending = null;

    function run() {
      const text = input.value;
      const tally = Object.fromEntries(dims.map((d) => [d.id, 0]));
      const found = Object.fromEntries(dims.map((d) => [d.id, []]));
      const unknown = [];
      let html = "";
      let last = 0;

      const gap = (s) => segment(s).map((seg) => {
        const w = seg.segment;
        if (!seg.isWordLike) return esc(w);
        const word = /^[\d.]+$/.test(w) ? false : isZh(w) ? w.length >= 2 && !ZH_STOP.has(w) : w.length >= 3 && !EN_STOP.has(w.toLowerCase());
        if (word && !unknown.includes(w)) unknown.push(w);
        return `<span class="tok">${esc(w)}</span>`;
      }).join("");

      for (const m of text.matchAll(matcher)) {
        const hit = m[0];
        const entry = entryFor(hit);
        if (!entry) continue;
        const ds = [...entry.dims];
        const via = entry.kind === "variant" && entry.term && entry.term !== hit ? `${hit} → ${entry.term}` : hit;
        ds.forEach((id) => { tally[id] += 1; found[id].push(entry.kind === "place" ? `${hit} (place)` : via); });
        const how = { code: "codebook term", variant: `variant of ${entry.term}`, place: "place name", custom: "added by you" }[entry.kind];
        html += gap(text.slice(last, m.index)) +
          `<mark class="dim-${ds[0]}${entry.kind === "custom" ? " is-custom" : ""}" title="${esc(how + ": " + ds.map(dimLabel).join(", "))}">${esc(hit)}</mark>`;
        last = m.index + hit.length;
      }
      html += gap(text.slice(last));

      marked.innerHTML = text.trim() ? html.replace(/\n/g, "<br>") : `<span class="demo__empty">Marked text appears here.</span>`;

      unknownEl.innerHTML = "";
      if (segmenter && unknown.length) {
        const head = el("p", "demo__unknown-head", "Not in the codebook. Select a word to add it:");
        const row = el("div", "demo__unknown-list");
        unknown.slice(0, 16).forEach((w) => {
          const b = el("button", "chip chip--quiet", esc(w));
          b.type = "button";
          b.setAttribute("aria-pressed", String(pending === w));
          b.addEventListener("click", () => { pending = pending === w ? null : w; run(); });
          row.appendChild(b);
        });
        unknownEl.append(head, row);
        if (pending && unknown.includes(pending)) {
          const pick = el("div", "demo__pick", `<span>Add <b>${esc(pending)}</b> to</span>`);
          pick.setAttribute("role", "group");
          pick.setAttribute("aria-label", `Choose a dimension for ${pending}`);
          dims.forEach((d) => {
            const b = el("button", `chip dim-${d.id}`, `<i aria-hidden="true"></i>${esc(d.label)}`);
            b.type = "button";
            b.addEventListener("click", () => {
              custom.set(isZh(pending) ? pending : pending.toLowerCase(), { dims: new Set([d.id]), term: pending, kind: "custom" });
              pending = null;
              compile();
              run();
            });
            pick.appendChild(b);
          });
          unknownEl.appendChild(pick);
        }
      }
      if (custom.size) {
        const reset = el("button", "demo__reset", `Remove the ${custom.size} word${custom.size > 1 ? "s" : ""} you added`);
        reset.type = "button";
        reset.addEventListener("click", () => { custom.clear(); compile(); run(); });
        unknownEl.appendChild(reset);
      }

      countsEl.innerHTML = dims.map((d) => `<li class="dim-${d.id}"><i aria-hidden="true"></i><span class="demo__dim">${esc(d.label)} <span lang="zh-Hans">${esc(d.zh)}</span></span><b>${tally[d.id]}</b>` +
        (found[d.id].length ? `<small>${found[d.id].map(esc).join(" · ")}</small>` : "") + `</li>`).join("");
    }

    input.addEventListener("input", () => { pending = null; run(); });
    document.querySelectorAll("[data-example]").forEach((b) => b.addEventListener("click", () => {
      input.value = b.dataset.example === "clear" ? "" : EXAMPLES[b.dataset.example];
      pending = null;
      run();
      input.focus({ preventScroll: true });
    }));
    input.value = EXAMPLES.g2;
    run();
  }

  const start = () => {
    [buildMigration, buildNetwork, buildMacro, buildShift, buildMined, buildDemo].forEach((fn) => {
      try { fn(); } catch (err) { console.error(fn.name, err); }
    });
  };
  if (document.readyState === "complete") start();
  else window.addEventListener("load", start);
})();
